project_id = "okeogjgqijbfkudfjadz"

[functions.import-loja-integrada]
verify_jwt = false

[functions.generate-sitemap]
verify_jwt = false

[functions.generate-knowledge-sitemap]
verify_jwt = false

[functions.create-user]
verify_jwt = true

[functions.seo-proxy]
verify_jwt = false

[functions.data-export]
verify_jwt = false

[functions.test-api-viewer]
verify_jwt = false

[functions.ai-metadata-generator]
verify_jwt = true