project_id = "okeogjgqijbfkudfjadz"

[functions.extract-pdf-text]
verify_jwt = false

[functions.ai-enrich-pdf-content]
verify_jwt = false

[functions.get-product-data]
verify_jwt = false

[functions.import-loja-integrada]
verify_jwt = false

[functions.sync-sistema-a]
verify_jwt = false

[functions.generate-sitemap]
verify_jwt = false

[functions.generate-knowledge-sitemap]
verify_jwt = false

[functions.create-user]
verify_jwt = true

[functions.seo-proxy]
verify_jwt = false

[functions.data-export]
verify_jwt = false

[functions.test-api-viewer]
verify_jwt = false

[functions.ai-metadata-generator]
verify_jwt = true

[functions.sync-knowledge-base]
verify_jwt = false

[functions.import-system-a-json]
verify_jwt = false

[functions.export-parametros-ia]
verify_jwt = false

[functions.knowledge-feed]
verify_jwt = false

[functions.generate-documents-sitemap]
verify_jwt = false

[functions.document-proxy]
verify_jwt = false

[functions.translate-content]
verify_jwt = false

[functions.backfill-keywords]
verify_jwt = false